# name: Hprofile Actions
# on: workflow_dispatch
# jobs: 
#   Testing:
#     runs-on: ubuntu-lastest
#     steps:
#       - name: Code CheckOut
#         uses: actions/checkout@v4

#       - name: Maven Test
#         run: mvn test
      
#       - name: Checkstyle
#         run: mvn checkstyle:checkstyle
name: Maven Build and Test

on:
  workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test with Maven
        run: mvn -B test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
