name: Hprofile Action
on: workflow_dispatch
jobs: 
  Testing:
    runs-on: ubuntu-lastest
    steps:
      - name: Code CheckOut
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
